name: Test cargo workspace

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    paths:
      - Cargo.toml
      - Cargo.lock
      # workspace members
      - crates/vc-issuer-mock-core/**
      - crates/vc-issuer-mock-rs/**
      - crates/vc-issuer-mock-http/**
      # workflow file
      - .github/workflows/test-cargo-workspace.yaml
  # For dependabot PRs
  pull_request_target:
    paths:
      - Cargo.toml
      - Cargo.lock
      # workspace members
      - crates/vc-issuer-mock-core/**
      - crates/vc-issuer-mock-rs/**
      - crates/vc-issuer-mock-http/**
      # workflow file
      - .github/workflows/test-cargo-workspace.yaml
  workflow_dispatch:

jobs:
  build:
    name: Test cargo workspace
    strategy:
      # Do not stop the workflow even if one of the matrix jobs fails.
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Test with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
