name: Test cargo workspace

env:
  PATHS_FILTER: |
    Cargo.toml
    Cargo.lock
    crates/vc-issuer-mock-core/**
    crates/vc-issuer-mock-rs/**
    crates/vc-issuer-mock-http/**
    .github/workflows/test-cargo-workspace.yml

on:
  pull_request:
    paths:
      - ${{ env.PATHS_FILTER }}
  # For dependabot PRs
  pull_request_target:
    paths:
      - ${{ env.PATHS_FILTER }}
  workflow_dispatch:

jobs:
  build:
    name: Test cargo workspace
    strategy:
      # Do not stop the workflow even if one of the matrix jobs fails.
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Rust toolchain
        run: |
          rustup set profile minimal
          rustup install stable
          rustup override set stable
          cargo install cross
      - name: Test with all features
        run: |
          cargo test --release --all-features
