name: Build and test vc-issuer-mock-core docker image

on:
  pull_request:
    paths:
      - Cargo.toml
      - Cargo.lock
      - crates/vc-issuer-mock-core/**
      # workflow file
      - .github/workflows/test-docker-vc-issuer-mock-core.yaml
      - .github/workflows/test-docker-vc-issuer-mock-core/**
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Build Docker image
      run: |
        docker build -t vc-issuer-mock-core -f docker/vc-issuer-mock-core/Dockerfile .

    - name: Run Docker container
      run: |
        docker run --rm -d --name vc-issuer-mock-core -p 8000:80 vc-issuer-mock-core

    - name: Test healthcheck endpoint
      run: |
        bash ./.github/workflows/test-docker-vc-issuer-mock-core/healthcheck.sh

    - name: Clean up
      if: always()
      run: |
        docker stop vc-issuer-mock-core
